### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by gtojty** [davebraze/FDButils#2]
* installing *source* package 'FDButils' ...
** R
Error in .install_package_code_files(".", instdir) : 
files in 'C:/Users/tg422/AppData/Local/Temp/1/RtmpKwXRV6/devtools3bd47ce77cc/davebraze-FDButils-0df6dc1/R' missing from 'Collate' field:
  mahalDist.R
ERROR: unable to collate and parse R files for package 'FDButils'
* removing 'C:/Users/tg422/Documents/R/win-library/3.3/FDButils'
Error: Command failed (1)

**Comment by davebraze** [comment]
resolved
